//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NVDieuHanh : NhanVien
{
	public IEnumerable<DoiTac> DoiTac;

	public bool ThemDoiTac(DoiTac dt)
	{
		throw new System.NotImplementedException();
	}

	public List<DoiTac> XemDanhSachDoiTac()
	{
		throw new System.NotImplementedException();
	}

	public List<DoiTac> XemDanhSachDoiTac(KieuDoiTac kdt)
	{
		throw new System.NotImplementedException();
	}

}

