//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using DataTranferObject;
    using System.Windows.Forms;
    using System.Data;
    public class dalKhachHang : dalObject
    {
        public bool ThemKhachHang(dtoKhachHang khachHang)
        {
            if (!this.Connect())
            {
                return false;
            }
            string sql = "INSERT INTO [dbo].[KHACHHANG]([TENDONVI],[NGUOIDAIDIEN],[GIOITINH],[EMAIL],[DIENTHOAI],[SONGUOI],[DIACHI],[LOAIKHACHHANG])VALUES('" +
                khachHang.TENDONVI + "','" + khachHang.NGUOIDAIDIEN + "','" + khachHang.GIOITINH + "','" + khachHang.EMAIL + "','" + khachHang.DIENTHOAI +
                "','" + khachHang.SONGUOI + "','" + khachHang.DIACHI + "','" + khachHang.LOAIKHACHHANG + "')";
            if (this.Write(sql))
            {
                this.Close();
                return true;
            }
            else
            {
                this.Close();
                return false;
            }
        }

        public bool SuaThongTinKhachHang(dtoKhachHang khachHang)
        {
            if (!this.Connect())
            {
                return false;
            }
            string sql = "UPDATE [dbo].[KHACHHANG]SET[TENDONVI] = '" + khachHang.TENDONVI +
      "',[NGUOIDAIDIEN] = '" + khachHang.NGUOIDAIDIEN +
      "',[GIOITINH] = '" + khachHang.GIOITINH +
      "',[EMAIL] = '" + khachHang.EMAIL +
      "',[DIENTHOAI] = '" + khachHang.DIENTHOAI +
      "',[SONGUOI] = '" + khachHang.SONGUOI +
      "',[DIACHI] = '" + khachHang.DIACHI +
      "',[LOAIKHACHHANG] = '" + khachHang.LOAIKHACHHANG +
      "'WHERE [MAKHACHHANG] = '" + khachHang.MAKHACHHANG + "'";
            if (this.Write(sql))
            {
                this.Close();
                return true;
            }
            else
            {
                this.Close();
                return false;
            }
        }

        public bool XoaKhachHang(int maKH)
        {
            if (!this.Connect())
            {
                return false;
            }
            string sql = "DELETE FROM [dbo].[KHACHHANG] WHERE [MAKHACHHANG]='" + maKH + "'";
            if (this.Write(sql))
            {
                this.Close();
                return true;
            }
            else
            {
                this.Close();
                return false;
            }
        }

        public List<dtoKhachHang> LayDanhSachKhachHang(int maNhanVien)
        {
            List<dtoKhachHang> ldtoKhachHang = new List<dtoKhachHang>();
            if (this.Connect())
            {
                string sql = "select * from [dbo].[KHACHHANG] where MANHANVIEN=" + maNhanVien;
                DataTable dtKhachHang = this.Read(sql);


                foreach (DataRow dr in dtKhachHang.Rows)
                {
                    dtoKhachHang dtoKhachHang = new dtoKhachHang();
                    dtoKhachHang.MAKHACHHANG = Int32.Parse(dr[0].ToString());
                    dtoKhachHang.MANHANVIEN = Int32.Parse(dr[1].ToString());
                    dtoKhachHang.TENDONVI = dr[2].ToString();
                    dtoKhachHang.NGUOIDAIDIEN = dr[3].ToString();
                    dtoKhachHang.GIOITINH = dr[4].ToString();
                    dtoKhachHang.EMAIL = dr[5].ToString();
                    dtoKhachHang.DIENTHOAI = dr[6].ToString();
                    dtoKhachHang.SONGUOI = Int32.Parse(dr[7].ToString());
                    dtoKhachHang.DIACHI = dr[8].ToString();
                    dtoKhachHang.LOAIKHACHHANG = dr[9].ToString();
                    ldtoKhachHang.Add(dtoKhachHang);
                }
                this.Close();

            }
            return ldtoKhachHang;

        }

    }
}

