//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataAccessLayer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using DataTranferObject;
	public class dalKhachHang : dalObject
	{
		public bool ThemKhachHang(dtoKhachHang khachHang)
		{

            return true;
		}

		public bool SuaThongTinKhachHang(dtoKhachHang khachHang)
		{
			throw new System.NotImplementedException();
		}

		public bool XoaKhachHang(int maKH)
		{
			throw new System.NotImplementedException();
		}

		public List<dtoKhachHang> LayDanhSachKhachHang(int maNhanVien)
		{
			throw new System.NotImplementedException();
		}

	}
}

