//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using DataTranferObject;
    using System.Data;
    public class dalNhanVien : dalObject
    {
        public bool ThemNhanVien(dtoNhanVien nhanVien)
        {
            if (!this.Connect())
            {
                return false;
            }
            string sql = "INSERT INTO [dbo].[NHANVIEN] ([MAPHONG],[HOTEN],[CMND],[DIACHI],[NGAYSINH],[QUEQUAN],[SODT],[EMAIL],[GIOITINH],[MATKHAU]) VALUES ("
                + nhanVien.MAPHONG + "," + nhanVien.HOTEN + "," + nhanVien.CMND + "," + nhanVien.DIACHI + "," + nhanVien.NGAYSINH + "," + nhanVien.QUEQUAN + "," + nhanVien.SODT + "," + nhanVien.EMAIL + "," + nhanVien.GIOITINH + "," + nhanVien.MATKHAU + ")";
            if (this.Write(sql))
            {
                this.Close();
                return true;
            }
            else
            {
                this.Close();
                return false;
            }
        }

        public bool XoaNhanVien(int maNhanVien)
        {
            if (!this.Connect())
            {
                return false;
            }
            string sql = "DELETE FROM [dbo].[NHANVIEN] WHERE [MANHANVIEN]=" + maNhanVien;
            if (this.Write(sql))
            {
                this.Close();
                return true;
            }
            else
            {
                this.Close();
                return false;
            }
        }

        public bool SuaThongTinNhanVien(dtoNhanVien nhanVien)
        {
            if (!this.Connect())
            {
                return false;
            }
            string sql = "UPDATE [dbo].[NHANVIEN]" +
              "SET [MAPHONG] = " +nhanVien.MAPHONG+
              " ,[HOTEN] = " +nhanVien.HOTEN+
              ",[CMND] = " +nhanVien.CMND+
              ",[DIACHI] = " +nhanVien.DIACHI+
              ",[NGAYSINH] = " +nhanVien.NGAYSINH+
              ",[QUEQUAN] = " +nhanVien.QUEQUAN+
              ",[SODT] = " +nhanVien.SODT+
              ",[EMAIL] = " +nhanVien.EMAIL+
              ",[GIOITINH] = " +nhanVien.GIOITINH+
              ",[MATKHAU] = " + nhanVien.MATKHAU+
              "WHERE [MANHANVIEN]="+nhanVien.MANHANVIEN;
            if (this.Write(sql))
            {
                this.Close();
                return true;
            }
            else
            {
                this.Close();
                return false;
            }
        }

        public bool DangNhap(int maNV, string matKhau)
        {
            if (!this.Connect())
            {
                return false;
            }
            string sql = "";
            return false;
        }

        public dtoNhanVien LayThongTinNhanVien(int maNhanVien)
        {
            throw new System.NotImplementedException();
        }

        public List<dtoNhanVien> LayDanhSachNhanVien(int maPhongBan)
        {
            throw new System.NotImplementedException();
        }

        public List<dtoNhanVien> LayDanhSachNhanVien()
        {
            throw new System.NotImplementedException();
        }

    }
}

