//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataAccessLayer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using DataTranferObject;
    using System.Data;
    using QuanLyDuLich.DAL;
	public class dalObject
	{
		protected virtual Connection connection
		{
			get;
			set;
		}

		public bool Connect()
		{
            try
            {
                this.connection = new Connection();
                this.connection.Open();                
            }
            catch 
            {
                return false;
            }
            return true;
            
		}

		public bool Close()
		{
			try
            {
                this.connection.Close();              
            }
            catch
            {
                return false;
            }
            return true;
		}

		public bool Write(string sql)
		{
            return this.connection.Write(sql);
		}

		public DataTable Read(string sql)
		{
            return this.connection.Read(sql);
		}

	}
}

