//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataAccessLayer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using DataTranferObject;
	public class dalTour : dalObject
	{
		public bool ThemTour(dtoTour tour)
		{
			throw new System.NotImplementedException();
		}

		public bool XoaTour(int maTour)
		{
			throw new System.NotImplementedException();
		}

		public bool CapNhatTour(int maTour, bool trangThai, string giaTour, string ghiChu)
		{
			throw new System.NotImplementedException();
		}

		public bool CapNhatTour(int maTour, bool trangThai, string ghiChu)
		{
			throw new System.NotImplementedException();
		}

		public bool CapNhatTour(dtoTour tour)
		{
			throw new System.NotImplementedException();
		}

		public bool CapNhatTour(int maTour, int maDoiTac)
		{
			throw new System.NotImplementedException();
		}

	}
}

