//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BLL
{
    using DataAccessLayer;
    using DataTranferObject;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

	public class ChiTietLichTrinh
	{
        private int maLichTrinh  = -1;
        private int maChiTietLichTrinh = -1;

        public int MaChiTietLichTrinh
        {
            get { return maChiTietLichTrinh; }
            set { maChiTietLichTrinh = value; }
        }
        public int MaLichTrinh
        {
            get { return maLichTrinh; }
            set { maLichTrinh = value; }
        }


        private string thoiGian;

        public string ThoiGian
        {
            get { return thoiGian; }
            set { thoiGian = value; }
        }

        private string noiDung;

        public string NoiDung
        {
            get { return noiDung; }
            set { noiDung = value; }
        }

        private DoiTac doiTac = new DoiTac();

        public DoiTac DoiTac
        {
            get { return doiTac; }
            set { doiTac = value; }
        }


        public ChiTietLichTrinh() { }

        public ChiTietLichTrinh(dtoChiTietLichTrinh dto)
        {
            this.ThoiGian = dto.THOIGIAN;
            this.NoiDung = dto.NOIDUNG;
            dalDoiTac dal_DoiTac = new dalDoiTac();
            this.DoiTac = new DoiTac(dal_DoiTac.LayDoiTac(dto.MADOITAC));
        }


        public bool Xoa()
        {
            dalChiTietLichTrinh dal = new dalChiTietLichTrinh();
            return dal.XoaCTLT(this.MaChiTietLichTrinh);
        }

        public void Luu()
        {
            DataAccessLayer.dalChiTietLichTrinh dal = new DataAccessLayer.dalChiTietLichTrinh();
            DataTranferObject.dtoChiTietLichTrinh dto = new DataTranferObject.dtoChiTietLichTrinh();

            dto.MADOITAC = doiTac.MaDoiTac;
            dto.NOIDUNG = noiDung;
            dto.THOIGIAN = thoiGian;
            dto.MALICHTRINH = maLichTrinh;

            dal.ThemCTLT(dto);
        }
	}
}

