//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BLL
{
    using DataAccessLayer;
    using DataTranferObject;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

	public class DiemDuLich
	{
        private int MaDiemDuLich;
        public int pMaDiemDuLich
        {
            get { return MaDiemDuLich; }
            set { MaDiemDuLich = value; }
        }
        private int MaNhanVien;
        public int pMaNhanVien
        {
            get { return MaNhanVien; }
            set { MaNhanVien = value; }
        }
        private string TenDiemDuLich;
        public string pTenDiemDuLich
        {
            get { return TenDiemDuLich; }
            set { TenDiemDuLich = value; }
        }
        private string MoTa;
        public string pMoTa
        {
            get { return MoTa; }
            set { MoTa = value; }
        }
        public DiemDuLich(int _maDiemDuLich, int _maNhanVien, string _tenDiemDuLich, string _moTa)
        {
            MaDiemDuLich = _maDiemDuLich;
            MaNhanVien = _maNhanVien;
            TenDiemDuLich = _tenDiemDuLich;
            MoTa = _moTa;
        }

        public DiemDuLich(dtoDiemDuLich _dtoDiemDuLich)
        {
            this.MaDiemDuLich = _dtoDiemDuLich.MADIEMDULICH;
            this.MaNhanVien = _dtoDiemDuLich.MANHANVIEN;
            this.MoTa = _dtoDiemDuLich.MOTA;
            this.TenDiemDuLich = _dtoDiemDuLich.TENDIEMDULICH;
        }
        public DiemDuLich() 
        {
        }
        public void setDiemDuLich(dtoDiemDuLich _diemDuLich)
        {
            MaNhanVien = _diemDuLich.MANHANVIEN;
            MaDiemDuLich = _diemDuLich.MADIEMDULICH;
            TenDiemDuLich = _diemDuLich.TENDIEMDULICH;
            MoTa = _diemDuLich.MOTA;
        }
        public List<dtoDiemDuLich> LayDanhSachDiemDuLich()
        {
            dalDiemDuLich dal = new dalDiemDuLich();
            return dal.LayDanhSachDiemDuLich();
        }
        public dtoDiemDuLich getdtoDiemDuLich()
        {
            dtoDiemDuLich _diemDuLich = new dtoDiemDuLich(MaDiemDuLich, MaNhanVien, TenDiemDuLich, MoTa);
            return _diemDuLich;
        }
		public bool CapNhat(dtoDiemDuLich ddl)
		{
            dalDiemDuLich _dalDiemDuLich = new dalDiemDuLich();
            _dalDiemDuLich.SuaThongTinDiemDuLich(ddl);
            return true;
		}

		public bool Luu()
		{
            dalDiemDuLich _dalDiemDuLich = new dalDiemDuLich();
            _dalDiemDuLich.ThemDiemDuLich(getdtoDiemDuLich());
            return true;
		}

		public bool Xoa(int maddl)
		{
            dalDiemDuLich _dalDiemDuLich = new dalDiemDuLich();
            _dalDiemDuLich.XoaDiemDuLich(maddl);
            return true;
		}

	}
}

