//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BLL
{
    using DataTranferObject;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

	public class DoiTac
	{
        private string tenDoiTac;

        public string TenDoiTac
        {
            get { return tenDoiTac; }
            set { tenDoiTac = value; }
        }

        private string nguoiLienHe;

        public string NguoiLienHe
        {
            get { return nguoiLienHe; }
            set { nguoiLienHe = value; }
        }

        private string soDT;

        public string SoDT
        {
            get { return soDT; }
            set { soDT = value; }
        }

        private string email;

        public string Email
        {
            get { return email; }
            set { email = value; }
        }

        private int maDoiTac;

        public int MaDoiTac
        {
            get { return maDoiTac; }
            set { maDoiTac = value; }
        }

        private string diaChi;

        public string DiaChi
        {
            get { return diaChi; }
            set { diaChi = value; }
        }

        private string danhGiaDoiTac;

        public string DanhGiaDoiTac
        {
            get { return danhGiaDoiTac; }
            set { danhGiaDoiTac = value; }
        }

        private string loaiDoiTac;

        public string LoaiDoiTac
        {
            get { return loaiDoiTac; }
            set { loaiDoiTac = value; }
        }

		public bool CapNhat()
		{
			throw new System.NotImplementedException();
		}

		public bool Luu()
		{
			throw new System.NotImplementedException();
		}

		public bool Xoa()
		{
			throw new System.NotImplementedException();
		}

		public dtoDoiTac LayThongTinDoiTac()
		{
			throw new System.NotImplementedException();
		}

	}
}

