//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BLL
{
    using DataTranferObject;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

	public class DoiTac
	{
		protected string TenDoiTac;

		protected string NguoiLienHe;

		protected string SoDT;

		protected string Email;

		protected int MaDoiTac;

		protected string DiaChi;

		protected string DanhGiaDoiTac;

		protected string LoaiDoiTac;

		public bool CapNhat()
		{
			throw new System.NotImplementedException();
		}

		public bool Luu()
		{
			throw new System.NotImplementedException();
		}

		public bool Xoa()
		{
			throw new System.NotImplementedException();
		}

		public dtoDoiTac LayThongTinDoiTac()
		{
			throw new System.NotImplementedException();
		}

	}
}

