//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BLL
{
    using DataAccessLayer;
    using DataTranferObject;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;

	public class KhachHang
	{
        private int MaKhachHang;
        private int MaNhanVien;

        public int pMaNhanVien
        {
            get { return MaNhanVien; }
            set { MaNhanVien = value; }
        }
        public int pMaKhachHang
        {
            get { return MaKhachHang; }
            set { MaKhachHang = value; }
        }        
        private string LoaiKhachHang;

        public string pLoaiKhachHang
        {
            get { return LoaiKhachHang; }
            set { LoaiKhachHang = value; }
        }

        private int SoNguoi;

        public int pSoNguoi
        {
            get { return SoNguoi; }
            set { SoNguoi = value; }
        }

        private string NguoiDaiDien;

        public string pNguoiDaiDien
        {
            get { return NguoiDaiDien; }
            set { NguoiDaiDien = value; }
        }

        private string SoDT;

        public string pSoDT
        {
            get { return SoDT; }
            set { SoDT = value; }
        }

        private string Email;

        public string pEmail
        {
            get { return Email; }
            set { Email = value; }
        }

        private string TenDonVi;

        public string pTenDonVi
        {
            get { return TenDonVi; }
            set { TenDonVi = value; }
        }


        private string DiaChi;

        public string pDiaChi
        {
            get { return DiaChi; }
            set { DiaChi = value; }
        }
        private string GioiTinh;

        public string pGioiTinh
        {
            get { return GioiTinh; }
            set { GioiTinh = value; }
        }
        public KhachHang(int _maKhachHang, string _tenDonVi, string _nguoiDaiDien, string _gioiTinh, 
            string _email, string _soDT, int _soNguoi, string _diaChi, string _loaiKhachHang)
        {
            MaKhachHang = _maKhachHang;
            LoaiKhachHang = _loaiKhachHang;
            SoNguoi = _soNguoi;
            NguoiDaiDien = _nguoiDaiDien;
            SoDT = _soDT;
            Email = _email;
            GioiTinh = _gioiTinh;
            TenDonVi = _tenDonVi;
            DiaChi = _diaChi;
        }
        public KhachHang()
        {             
        }

        public KhachHang(dtoKhachHang dto)
        {
            this.DiaChi = dto.DIACHI;
            this.Email = dto.EMAIL;
            this.LoaiKhachHang = dto.LOAIKHACHHANG;
            this.NguoiDaiDien = dto.NGUOIDAIDIEN;
            this.SoDT = dto.DIENTHOAI;
            this.SoNguoi = dto.SONGUOI;
            this.TenDonVi = dto.TENDONVI;
        }

        public void setKhachHang(dtoKhachHang _khachHang)
        {
            MaKhachHang = _khachHang.MAKHACHHANG;
            TenDonVi = _khachHang.TENDONVI;
            NguoiDaiDien = _khachHang.NGUOIDAIDIEN;
            GioiTinh = _khachHang.GIOITINH;
            Email = _khachHang.EMAIL;
            SoDT = _khachHang.DIENTHOAI;
            SoNguoi = _khachHang.SONGUOI;
            DiaChi = _khachHang.DIACHI;
            LoaiKhachHang = _khachHang.LOAIKHACHHANG;
        }
        dtoKhachHang getdtoKhachHang() 
        {
            dtoKhachHang _khachHang = new dtoKhachHang(MaKhachHang, TenDonVi, NguoiDaiDien, GioiTinh, Email, SoDT, SoNguoi, DiaChi, LoaiKhachHang);
            return _khachHang;
        }
		public bool CapNhat()
		{
            dalKhachHang _dalKhachHang = new dalKhachHang();
            _dalKhachHang.SuaThongTinKhachHang(getdtoKhachHang());
            return true;
		}

		public bool Luu()
		{
            dalKhachHang _dalKhachHang = new dalKhachHang();
            _dalKhachHang.ThemKhachHang(getdtoKhachHang());
            return true;
		}

		public bool Xoa()
		{
            dalKhachHang _dalKhachHang = new dalKhachHang();
            _dalKhachHang.XoaKhachHang(MaKhachHang);
            return true;
		}

	}
}

