//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace QuanLyDuLich.BLL
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class NVSale : NhanVien
	{
		public virtual IEnumerable<Tour> tour
		{
			get;
			set;
		}

		public virtual IEnumerable<DiemDuLich> DiemDuLich
		{
			get;
			set;
		}

		public IEnumerable<DiemDuLich> diemDuLich;

		public bool ThemKhachHang(KhachHang kh)
		{
			throw new System.NotImplementedException();
		}

		public bool ThemTour(Tour tour)
		{
			throw new System.NotImplementedException();
		}

		public bool ThemDiemDuLich(DiemDuLich ddl)
		{
			throw new System.NotImplementedException();
		}

		public KhachHang XemThongTinKhachHang(int makh)
		{
			throw new System.NotImplementedException();
		}

	}
}

