//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BLL
{
	using DataAccessLayer;
using DataTranferObject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

	public class PhongBan
	{
        dalPhongBan dalpb = new dalPhongBan();
		protected string TenPhongBan;
        public string pTenPhongBan
        {
            get { return TenPhongBan; }
            set { TenPhongBan = value; }
        }
		protected string MaPhongBan;
        public string pMaPhongBan
        {
            get { return MaPhongBan; }
            set { MaPhongBan = value; }
        }
        public List<dtoPhongBan> LayDanhSachPhongBan()
        {
            return dalpb.LayDanhSachPhong();
        }
        public dtoPhongBan LayThongTinPhong(string maphong)
        {
            return dalpb.LayThongTinPhong(maphong);
        }
        public bool SuaThongTinPhong(dtoPhongBan dtopb)
        {
            return dalpb.SuaThongTinPhong(dtopb);
        }
        public bool ThemPhong(dtoPhongBan dtopb)
        {
            return dalpb.ThemPhong(dtopb);
        }
        public bool XoaPhong(dtoPhongBan dtopb)
        {
            return XoaPhong(dtopb);
        }
		public IEnumerable<NhanVien> NhanVien;

	}
}

