//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataTranferObject
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dtoDoiTac
	{
		public int MADOITAC
		{
			get;
			set;
		}

		public int MANHANVIEN
		{
			get;
			set;
		}

		public string TENDOITAC
		{
			get;
			set;
		}

		public string NGUOILIENHE
		{
			get;
			set;
		}

		public string DIENTHOAI
		{
			get;
			set;
		}

		public string DANHGIADOITAC
		{
			get;
			set;
		}

		public string DIACHI
		{
			get;
			set;
		}

		public string EMAIL
		{
			get;
			set;
		}

		public string LOAIDOITAC
		{
			get;
			set;
		}

	}
}

