//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataTranferObject
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dtoKhachHang
	{
		public int MAKHACHHANG
		{
			get;
			set;
		}

		public string TENDONVI
		{
			get;
			set;
		}

		public string NGUOIDAIDIEN
		{
			get;
			set;
		}

		public string GIOITINH
		{
			get;
			set;
		}

		public string EMAIL
		{
			get;
			set;
		}

		public string DIENTHOAI
		{
			get;
			set;
		}

		public int SONGUOI
		{
			get;
			set;
		}

		public string DIACHI
		{
			get;
			set;
		}

		public string LOAIKHACHHANG
		{
			get;
			set;
		}

	}
}

