//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataTranferObject
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dtoKhachHang
	{
		public int MAKHACHHANG
		{
			get;
			set;
		}
        public int MANHANVIEN
        {
            get;
            set;
        }

		public string TENDONVI
		{
			get;
			set;
		}
		public string NGUOIDAIDIEN
		{
			get;
			set;
		}
		public string GIOITINH
		{
			get;
			set;
		}
		public string EMAIL
		{
			get;
			set;
		}
		public string DIENTHOAI
		{
			get;
			set;
		}
		public int SONGUOI
		{
			get;
			set;
		}
		public string DIACHI
		{
			get;
			set;
		}
		public string LOAIKHACHHANG
		{
			get;
			set;
		}
        public int TRANGTHAI
        {
            get;
            set;
        }
        public dtoKhachHang(int _maNhanVien,int _maKhachHang, string _tenDonVi, string _nguoiDaiDien, string _gioiTinh,string _email, string _dienThoai,int _soNguoi,string _diaChi,string _loaiKhachHang,int _trangthai)
        {
            MANHANVIEN = _maNhanVien;
            MAKHACHHANG = _maKhachHang;
            TENDONVI = _tenDonVi;
            NGUOIDAIDIEN = _nguoiDaiDien;
            GIOITINH = _gioiTinh;
            EMAIL = _email;
            DIENTHOAI = _dienThoai;
            SONGUOI = _soNguoi;
            DIACHI = _diaChi;
            LOAIKHACHHANG = _loaiKhachHang;
            TRANGTHAI = _trangthai;
        }
        public dtoKhachHang() { }        
	}
}

