//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataTranferObject
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dtoNhanVien
	{
		public int MANHANVIEN
		{
			get;
			set;
		}

		public int MAPHONG
		{
			get;
			set;
		}

		public string HOTEN
		{
			get;
			set;
		}

		public string CMND
		{
			get;
			set;
		}

		public string DIACHI
		{
			get;
			set;
		}

		public DateTime NGAYSINH
		{
			get;
			set;
		}

		public string QUEQUAN
		{
			get;
			set;
		}

		public string SODT
		{
			get;
			set;
		}
        public string MATKHAU
        {
            get;
            set;
        }
		public string EMAIL
		{
			get;
			set;
		}

		public string GIOITINH
		{
			get;
			set;
		}

	}
}

