//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DiemDuLich
{
	protected string MoTa
	{
		get;
		set;
	}

	protected string TenDiemDuLich
	{
		get;
		set;
	}

	public bool CapNhat()
	{
		throw new System.NotImplementedException();
	}

	public bool Luu()
	{
		throw new System.NotImplementedException();
	}

	public bool Xoa()
	{
		throw new System.NotImplementedException();
	}

}

