//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GiamDoc : NhanVien
{
	public bool ThemNhanVien(ModelingProject2::NhanVien nv, ModelingProject2::PhongBan pb)
	{
		throw new System.NotImplementedException();
	}

	public bool SuaThongTinNhanVien(ModelingProject2::NhanVien nv)
	{
		throw new System.NotImplementedException();
	}

}

