//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class KhachHang
{
	protected string LoaiKhachHang;

	protected int SoNguoi;

	protected string NguoiDaiDien;

	protected string SoDT;

	protected string Email;

	protected string TenDonVi;

	protected string DiaChi;

	public bool CapNhat()
	{
		throw new System.NotImplementedException();
	}

	public bool Luu()
	{
		throw new System.NotImplementedException();
	}

	public bool Xoa()
	{
		throw new System.NotImplementedException();
	}

}

