//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NhanVien
{
	protected string HoTen;

	protected int MaNhanVien;

	protected string SoDT;

	protected string DiaChi;

	protected string QueQuan;

	protected string CMND;

	protected string Email;

	protected DateTime NgaySinh;

	protected string GioiTinh;

	protected string MatKhau;

	public bool DangNhap(string maNv, string mk)
	{
		throw new System.NotImplementedException();
	}

	public void DangXuat()
	{
		throw new System.NotImplementedException();
	}

	public LoaiNhanVien LayLoaiNV()
	{
		throw new System.NotImplementedException();
	}

	public bool CapNhat()
	{
		throw new System.NotImplementedException();
	}

	public bool Luu()
	{
		throw new System.NotImplementedException();
	}

	public bool Xoa()
	{
		throw new System.NotImplementedException();
	}

	public Tour ChonTourCanXem(int matour)
	{
		throw new System.NotImplementedException();
	}

	public DoiTac ChonDoiTacCanXem(int madoitac)
	{
		throw new System.NotImplementedException();
	}

}

