//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BLL
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class GiamDoc : NhanVien
	{
		public IEnumerable<NhanVien> NhanVien;

		public NhanVien ChonNhanVien(int manv)
		{
			throw new System.NotImplementedException();
		}

		public bool CapNhatThongTinNhanVien(NhanVien nv, dtoNhanVien data)
		{
			throw new System.NotImplementedException();
		}

		public bool ThemNhanVien(dtoNhanVien data)
		{
			throw new System.NotImplementedException();
		}

		public Tour ChonTourCanDuyet(int matour)
		{
			throw new System.NotImplementedException();
		}

		public void NhapGiaTour(Tour tour)
		{
			throw new System.NotImplementedException();
		}

	}
}

