//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BLL
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class NVDieuHanh : NhanVien
	{
		public IEnumerable<DoiTac> DoiTac;

		public bool CapNhat(DoiTac doiTac, object data dtoDoiTac)
		{
			throw new System.NotImplementedException();
		}

		public DoiTac ChonDoiTac(int ma)
		{
			throw new System.NotImplementedException();
		}

		public bool ThemDoiTac(dtoDoiTac data)
		{
			throw new System.NotImplementedException();
		}

		public Tour ChonTourCanDuyet(int matour)
		{
			throw new System.NotImplementedException();
		}

		public bool DuyetTour(Tour tour)
		{
			throw new System.NotImplementedException();
		}

	}
}

