//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataTranferObject
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dtoChiTietLichTrinh
	{
		public int MACHITIETLICHTRINH
		{
			get;
			set;
		}

		public int MALICHTRINH
		{
			get;
			set;
		}

		public int MADOITAC
		{
			get;
			set;
		}

		public string NOIDUNG
		{
			get;
			set;
		}

		public string THOIGIAN
		{
			get;
			set;
		}

	}
}

