//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataTranferObject
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dtoDiemDuLich
	{
		public int MADIEMDULICH
		{
			get;
			set;
		}

		public int MANHANVIEN
		{
			get;
			set;
		}

		public string TENDIEMDULICH
		{
			get;
			set;
		}

		public string MOTA
		{
			get;
			set;
		}

	}
}

