//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataTranferObject
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dtoLichTrinh
	{
		public int MALICHTRINH
		{
			get;
			set;
		}

		public int MATOUR
		{
			get;
			set;
		}

		public string TENLICHTRINH
		{
			get;
			set;
		}

		public int NGAY
		{
			get;
			set;
		}

	}
}

