//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataTranferObject
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dtoTour
	{
		public int MATOUR
		{
			get;
			set;
		}

		public Interger MANHANVIEN
		{
			get;
			set;
		}

		public int MAKHACHHANG
		{
			get;
			set;
		}

		public int NHAXE
		{
			get;
			set;
		}

		public int HUONGDANVIEN
		{
			get;
			set;
		}

		public string TENTOUR
		{
			get;
			set;
		}

		public string THOIGIAN
		{
			get;
			set;
		}

		public DateTime NGAYDI
		{
			get;
			set;
		}

		public int TONGGIATOUR
		{
			get;
			set;
		}

		public string TRANGTHAI
		{
			get;
			set;
		}

		public string UUDAI
		{
			get;
			set;
		}

		public string GHICHU
		{
			get;
			set;
		}

	}
}

