//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataAccessLayer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dalChiTietLichTrinh : dalObject
	{
		public bool ThemCTLT(dtoChiTietLichTrinh ctlt)
		{
			throw new System.NotImplementedException();
		}

		public bool SuaCTLT(dtoChiTietLichTrinh ctlt)
		{
			throw new System.NotImplementedException();
		}

		public bool XoaCTLT(int mactlt)
		{
			throw new System.NotImplementedException();
		}

		public bool ThemDanhSachCTLT(List<dtoChiTietLichTrinh> dsctlt)
		{
			throw new System.NotImplementedException();
		}

		public List<dtoChiTietLichTrinh> LayDanhSachCTLT(int maLichTrinh)
		{
			throw new System.NotImplementedException();
		}

	}
}

