//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataAccessLayer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dalDoiTac : dalObject
	{
		public bool ThemDoiTac(dtoDoiTac doiTac)
		{
			throw new System.NotImplementedException();
		}

		public bool SuaThongTinDoiTac(dtoDoiTac doiTac)
		{
			throw new System.NotImplementedException();
		}

		public bool XoaDoiTac(int maDoiTac)
		{
			throw new System.NotImplementedException();
		}

		public List<dtoDoiTac> LayDanhSachDoiTac(int maNhanVien)
		{
			throw new System.NotImplementedException();
		}

		public List<dtoDoiTac> LayDanhSachDoiTac()
		{
			throw new System.NotImplementedException();
		}

	}
}

