//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataAccessLayer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dalDiemDuLich : dalObject
	{
		public bool ThemDiemDuLich(dtoDiemDuLich diemDuLich)
		{
			throw new System.NotImplementedException();
		}

		public bool XoaDiemDuLich(int maDDL)
		{
			throw new System.NotImplementedException();
		}

		public List<dtoDiemDuLich> LayDanhSachDiemDuLich(int maNV)
		{
			throw new System.NotImplementedException();
		}

		public bool SuaThongTinDiemDuLich(dtoDiemDuLich ddl)
		{
			throw new System.NotImplementedException();
		}

		public List<dtoDiemDuLich> LayDanhSachDiemDuLich()
		{
			throw new System.NotImplementedException();
		}

	}
}

