//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataAccessLayer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dalLichTrinh : dalObject
	{
		public bool ThemLichTrinh(dtoLichTrinh lichTrinh)
		{
			throw new System.NotImplementedException();
		}

		public bool SuaLichTrinh(dtoLichTrinh lichTrinh)
		{
			throw new System.NotImplementedException();
		}

		public bool XoaLichTrinh(int malt)
		{
			throw new System.NotImplementedException();
		}

		public bool ThemDanhSachLichTrinh(List<dtoLichTrinh> dslt)
		{
			throw new System.NotImplementedException();
		}

		public List<dtoLichTrinh> LayDanhSachLichTrinh(int maTour)
		{
			throw new System.NotImplementedException();
		}

	}
}

