//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataAccessLayer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dalNhanVien : dalObject
	{
		public bool ThemNhanVien(dtoNhanVien nhanVien)
		{
			throw new System.NotImplementedException();
		}

		public bool XoaNhanVien(int maNhanVien)
		{
			throw new System.NotImplementedException();
		}

		public bool SuaThongTinNhanVien(dtoNhanVien nhanVien)
		{
			throw new System.NotImplementedException();
		}

		public bool DangNhap(string email, string matKhau)
		{
			throw new System.NotImplementedException();
		}

		public dtoNhanVien LayThongTinNhanVien(int maNhanVien)
		{
			throw new System.NotImplementedException();
		}

		public List<dtoNhanVien> LayDanhSachNhanVien(int maPhongBan)
		{
			throw new System.NotImplementedException();
		}

		public List<dtoNhanVien> LayDanhSachNhanVien()
		{
			throw new System.NotImplementedException();
		}

	}
}

