//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace DataAccessLayer
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class dalObject
	{
		protected virtual Connection connection
		{
			get;
			set;
		}

		public bool Connect()
		{
			throw new System.NotImplementedException();
		}

		public bool Close()
		{
			throw new System.NotImplementedException();
		}

		public bool Write(string sql)
		{
			throw new System.NotImplementedException();
		}

		public DataTable Read(string sql)
		{
			throw new System.NotImplementedException();
		}

	}
}

